[project]
name = "fair-ca-visualization"
version = "0.3.0"
description = "FAIR COMBINE Archive Indicators"
readme = "README.md"
requires-python = ">=3.14"
authors = [
	{name="Matthias König", email="konigmatt@googlemail.com"}
]
maintainers = [
	{name="Matthias König", email="konigmatt@googlemail.com"}
]
classifiers = [
	"Development Status :: 4 - Beta",
	"Intended Audience :: Science/Research",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
    "Programming Language :: Python :: 3.14",
	"Programming Language :: Python :: Implementation :: CPython",
	"Topic :: Scientific/Engineering",
	"Topic :: Scientific/Engineering :: Bio-Informatics",
]
keywords = [
	"modeling",
	"standardization",
	"COMBINE",
	"FAIR",
]
dependencies = [
	"pyarrow>=23.0.1",
    "pandas<3",
    "rich>=14.3.3",
    "openpyxl>=3.1.5",
    "plotly>=6.6.0",
    "streamlit>=1.55.0",
]

[project_urls]
Homepage = "https://github.com/matthiaskoenig/fair-ca-visualization"
Repository = "https://github.com/matthiaskoenig/fair-ca-visualization"
Documentation = "https://github.com/matthiaskoenig/fair-ca-visualization"
Issues = "https://github.com/matthiaskoenig/fair-ca-visualization/issues"
